// src/lib/emailReportService.ts
// Email service for report emails — reads SMTP from env vars, attaches .xlsx

import nodemailer from 'nodemailer'
import { buildYtdReport, type ReportPayload } from '@/lib/financeReport'
import { DEFAULT_TIMEZONE } from '@/lib/timezone'
import { generateExcelBuffer } from './reportExcel'
import { formatCurrency } from '@/lib/financeShared'

export interface EnvSmtpConfig {
  host: string
  port: number
  username: string
  password: string
  fromEmail: string
}

/**
 * Read SMTP configuration from environment variables.
 * Returns null if not configured.
 */
export function getEnvSmtpConfig(): EnvSmtpConfig | null {
  const host = process.env.SMTP_HOST
  const portStr = process.env.SMTP_PORT
  const username = process.env.SMTP_USER
  const password = process.env.SMTP_PASS
  const fromEmail = process.env.SMTP_FROM

  if (!host || !username || !password) return null

  return {
    host,
    port: portStr ? parseInt(portStr, 10) : 587,
    username,
    password,
    fromEmail: fromEmail || username,
  }
}

/**
 * Build HTML email body from a report payload.
 */
function buildEmailBody(report: ReportPayload): string {
  const fmt = (n: number) => formatCurrency(n)

  let entityRows = ''
  for (const section of report.sections) {
    entityRows += `
      <tr>
        <td style="padding:4px 8px;font-weight:bold">${section.name}</td>
        <td style="padding:4px 8px;text-align:right">${fmt(section.income.subtotal)}</td>
        <td style="padding:4px 8px;text-align:right">${fmt(section.expenses.subtotal)}</td>
        <td style="padding:4px 8px;text-align:right;color:${section.nett >= 0 ? '#375623' : '#C00000'};font-weight:bold">${fmt(section.nett)}</td>
      </tr>`
  }

  let taxHtml = ''
  if (report.tax && report.tax.byMember.length > 0) {
    let memberRows = ''
    for (const m of report.tax.byMember) {
      const refundOrOwing = -(m.estimatedTaxPayable - m.paygWithheld - m.taxPayments)
      memberRows += `
        <tr>
          <td style="padding:4px 8px">${m.memberName}</td>
          <td style="padding:4px 8px;text-align:right">${fmt(m.taxableIncome)}</td>
          <td style="padding:4px 8px;text-align:right">${fmt(m.estimatedTaxPayable)}</td>
          <td style="padding:4px 8px;text-align:right;color:${refundOrOwing >= 0 ? '#375623' : '#C00000'};font-weight:bold">${fmt(refundOrOwing)}</td>
        </tr>`
    }
    taxHtml = `
      <h3 style="margin-top:24px;color:#2E75B6">Tax Summary</h3>
      <table style="width:100%;border-collapse:collapse;font-size:10pt">
        <thead>
          <tr style="background:#D9D9D9"><th style="padding:4px 8px;text-align:left">Member</th><th style="padding:4px 8px;text-align:right">Taxable Income</th><th style="padding:4px 8px;text-align:right">Est. Tax Payable</th><th style="padding:4px 8px;text-align:right">Est. Refund / (Owing)</th></tr>
        </thead>
        <tbody>${memberRows}</tbody>
      </table>`
  }

  return `
    <div style="font-family:-apple-system,'Segoe UI',Roboto,sans-serif;max-width:600px;margin:0 auto">
      <h2 style="color:#2E75B6">Homebase Finance Report</h2>
      <p style="color:#666">${report.meta.periodLabel} (${report.meta.financialYear}) — ${report.meta.monthsComplete} of 12 months</p>

      <h3 style="margin-top:24px;color:#2E75B6">Summary by Entity</h3>
      <table style="width:100%;border-collapse:collapse;font-size:10pt">
        <thead>
          <tr style="background:#D9D9D9">
            <th style="padding:4px 8px;text-align:left">Entity</th>
            <th style="padding:4px 8px;text-align:right">Income</th>
            <th style="padding:4px 8px;text-align:right">Expenses</th>
            <th style="padding:4px 8px;text-align:right">NETT</th>
          </tr>
        </thead>
        <tbody>
          ${entityRows}
          <tr style="font-weight:bold;background:#BDD7EE">
            <td style="padding:4px 8px">Total</td>
            <td style="padding:4px 8px;text-align:right">${fmt(report.totals.totalIncome)}</td>
            <td style="padding:4px 8px;text-align:right">${fmt(report.totals.totalExpenses)}</td>
            <td style="padding:4px 8px;text-align:right;color:${report.totals.totalNett >= 0 ? '#375623' : '#C00000'}">${fmt(report.totals.totalNett)}</td>
          </tr>
        </tbody>
      </table>

      ${taxHtml}

      <p style="margin-top:24px;font-size:9pt;color:#999">This report was automatically generated by Homebase Finance.</p>
    </div>`
}

/**
 * Send a report email with xlsx attachment.
 * Reads SMTP config from environment variables.
 */
export async function sendReportEmail({
  familyId,
  year,
  recipients,
  note,
  snapshotId,
  fyStartMonth = 7,
  tz = DEFAULT_TIMEZONE,
}: {
  familyId: string
  year: string
  recipients: string[]
  note?: string
  snapshotId?: string
  // FY start month + family tz must match the ones the caller resolved the
  // report `year` against, so the emailed workbook covers the same period the
  // caller intended (omitting them silently defaulted to a July/Sydney FY — P9-FC-02).
  fyStartMonth?: number
  tz?: string
}): Promise<{ success: true; emailIds: string[] } | { success: false; error: string }> {
  try {
    const smtp = getEnvSmtpConfig()
    if (!smtp) {
      return { success: false, error: 'SMTP not configured. Set SMTP_HOST, SMTP_USER, SMTP_PASS environment variables.' }
    }

    // Build the report data
    const report = await buildYtdReport(familyId, year, fyStartMonth, tz)

    // Generate excel attachment buffer
    const excelBuf = generateExcelBuffer(report)

    const transporter = nodemailer.createTransport({
      host: smtp.host,
      port: smtp.port,
      secure: smtp.port === 465,
      auth: {
        user: smtp.username,
        pass: smtp.password,
      },
    })

    const subject = `Homebase Finance — YTD ${report.meta.periodLabel} (${report.meta.financialYear})`
    const html = buildEmailBody(report) + (note ? `<p style="margin-top:16px;padding:12px;background:#f5f5f5;border-radius:6px">${note}</p>` : '')

    const emailIds: string[] = []

    for (const recipient of recipients) {
      await transporter.sendMail({
        from: smtp.fromEmail,
        to: recipient,
        subject,
        html,
        attachments: [
          {
            filename: `Homebase_Finance_${report.meta.financialYear.replace('/', '-')}.xlsx`,
            content: excelBuf,
            contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          },
        ],
      })
      emailIds.push(recipient)
    }

    return { success: true, emailIds }
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error'
    return { success: false, error: message }
  }
}
